name: "deploy"
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    container:
      image: node:15.5.1-alpine
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
            ref: master
        - name: deploy
          run: ./.github/workflows/deploy.sh
